// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSo02ev5DvdAVvsbyub4OnPcVVUAXRtEA',
    appId: '1:827936159618:web:0b802f0c04678667c4019b',
    messagingSenderId: '827936159618',
    projectId: 'sendsay-app-test',
    authDomain: 'sendsay-app-test.firebaseapp.com',
    storageBucket: 'sendsay-app-test.firebasestorage.app',
    measurementId: 'G-GBXGY02BQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlnjvoXXJ6uzR--vBXmdZ_wSaMJ1srASQ',
    appId: '1:827936159618:android:abb2265004fad8f8c4019b',
    messagingSenderId: '827936159618',
    projectId: 'sendsay-app-test',
    storageBucket: 'sendsay-app-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqXdZkKNCMH_YSTsqJEfWtELIAWYxOgY',
    appId: '1:827936159618:ios:0eefe13c36dbfc25c4019b',
    messagingSenderId: '827936159618',
    projectId: 'sendsay-app-test',
    storageBucket: 'sendsay-app-test.firebasestorage.app',
    iosBundleId: 'ru.sendsay.SendsayTests',
  );
}
